[phases.setup]
nixPkgs = ["...", "sqlite"]

[phases.install]
cmds = ["npm ci --ignore-scripts", "npx prisma generate"]

[phases.build]
cmds = [
  "npx next build",
  "cp -r .next/static .next/standalone/.next/",
  "cp -r public .next/standalone/",
  "mkdir -p .next/standalone/db"
]

[start]
cmd = "cd .next/standalone && npx prisma db push --skip-generate 2>/dev/null; node server.js"